<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://service.main.idls.pcci.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://service.main.idls.pcci.com" xmlns:intf="http://service.main.idls.pcci.com" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="importIFMSDataRequest">

      <wsdl:part name="startDate" type="xsd:string"/>

      <wsdl:part name="endDate" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="importIFMSDataResponse">

      <wsdl:part name="importIFMSDataReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:portType name="ImportTransactionService">

      <wsdl:operation name="importIFMSData" parameterOrder="startDate endDate">

         <wsdl:input message="impl:importIFMSDataRequest" name="importIFMSDataRequest"/>

         <wsdl:output message="impl:importIFMSDataResponse" name="importIFMSDataResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="ImportTransactionServiceSoapBinding" type="impl:ImportTransactionService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="importIFMSData">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="importIFMSDataRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://service.main.idls.pcci.com" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="importIFMSDataResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://service.main.idls.pcci.com" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="ImportTransactionServiceService">

      <wsdl:port binding="impl:ImportTransactionServiceSoapBinding" name="ImportTransactionService">

         <wsdlsoap:address location="http://192.168.0.206:8080/idls/services/ImportTransactionService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
