//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.20 at 06:11:16 PM SGT 
//


package com.pcci.idls.maintenance.securitytype.jaxbmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SecurityTypeService element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="SecurityTypeService">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}transaction"/>
 *           &lt;element ref="{}SecurityTypeID"/>
 *           &lt;element ref="{}SecurityDesc"/>
 *           &lt;element ref="{}InvestmentType"/>
 *           &lt;element ref="{}LastUserCode"/>
 *           &lt;element ref="{}LastUpdate"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transaction",
    "securityTypeID",
    "securityDesc",
    "investmentType",
    "lastUserCode",
    "lastUpdate"
})
@XmlRootElement(name = "SecurityTypeService")
public class SecurityTypeServiceModel {

    @XmlElement(required = true)
    protected Transaction transaction;
    @XmlElement(name = "SecurityTypeID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String securityTypeID;
    @XmlElement(name = "SecurityDesc", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String securityDesc;
    @XmlElement(name = "InvestmentType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String investmentType;
    @XmlElement(name = "LastUserCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lastUserCode;
    @XmlElement(name = "LastUpdate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lastUpdate;

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link Transaction }
     *     
     */
    public Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transaction }
     *     
     */
    public void setTransaction(Transaction value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the securityTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityTypeID() {
        return securityTypeID;
    }

    /**
     * Sets the value of the securityTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityTypeID(String value) {
        this.securityTypeID = value;
    }

    /**
     * Gets the value of the securityDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityDesc() {
        return securityDesc;
    }

    /**
     * Sets the value of the securityDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityDesc(String value) {
        this.securityDesc = value;
    }

    /**
     * Gets the value of the investmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvestmentType() {
        return investmentType;
    }

    /**
     * Sets the value of the investmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvestmentType(String value) {
        this.investmentType = value;
    }

    /**
     * Gets the value of the lastUserCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUserCode() {
        return lastUserCode;
    }

    /**
     * Sets the value of the lastUserCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUserCode(String value) {
        this.lastUserCode = value;
    }

    /**
     * Gets the value of the lastUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdate() {
        return lastUpdate;
    }

    /**
     * Sets the value of the lastUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdate(String value) {
        this.lastUpdate = value;
    }

}
