//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.19 at 03:28:45 PM SGT 
//


package com.pcci.idls.processtransaction.transfer.trxentries.jaxbmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IDLSTrxEntries element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="IDLSTrxEntries">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}IDLSTrxEntry" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idlsTrxEntry"
})
@XmlRootElement(name = "IDLSTrxEntries")
public class JBOIDLSTrxEntries {

    @XmlElement(name = "IDLSTrxEntry", required = true)
    protected List<JBOIDLSTrxEntry> idlsTrxEntry;

    /**
     * Gets the value of the idlsTrxEntry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the idlsTrxEntry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIDLSTrxEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JBOIDLSTrxEntry }
     * 
     * 
     */
    public List<JBOIDLSTrxEntry> getIDLSTrxEntry() {
        if (idlsTrxEntry == null) {
            idlsTrxEntry = new ArrayList<JBOIDLSTrxEntry>();
        }
        return this.idlsTrxEntry;
    }

}
