//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.19 at 03:28:45 PM SGT 
//


package com.pcci.idls.processtransaction.transfer.trxentries.jaxbmodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pcci.idls.processtransaction.transfer.trxentries.jaxbmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TrxIMAXAcctNormalBal_QNAME = new QName("", "TrxIMA_XAcctNormalBal");
    private final static QName _TrxDate_QNAME = new QName("", "TrxDate");
    private final static QName _TrxStartDate_QNAME = new QName("", "TrxStartDate");
    private final static QName _TrxDebit_QNAME = new QName("", "TrxDebit");
    private final static QName _Rn_QNAME = new QName("", "rn");
    private final static QName _TrxIMAAcctCode_QNAME = new QName("", "TrxIMA_AcctCode");
    private final static QName _TrxTotal_QNAME = new QName("", "TrxTotal");
    private final static QName _TrxCredit_QNAME = new QName("", "TrxCredit");
    private final static QName _TrxIMAAcctNormalBal_QNAME = new QName("", "TrxIMA_AcctNormalBal");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _TrxDesc_QNAME = new QName("", "TrxDesc");
    private final static QName _TrxIMAXAcctCode_QNAME = new QName("", "TrxIMA_XAcctCode");
    private final static QName _TrxFrom_QNAME = new QName("", "TrxFrom");
    private final static QName _TrxEndDate_QNAME = new QName("", "TrxEndDate");
    private final static QName _TrxJournal_QNAME = new QName("", "TrxJournal");
    private final static QName _TrxRefNo_QNAME = new QName("", "TrxRefNo");
    private final static QName _TrxType_QNAME = new QName("", "TrxType");
    private final static QName _LastUserCode_QNAME = new QName("", "LastUserCode");
    private final static QName _LastUpdate_QNAME = new QName("", "LastUpdate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pcci.idls.processtransaction.transfer.trxentries.jaxbmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link JBOIDLSTrxEntry }
     * 
     */
    public JBOIDLSTrxEntry createIDLSTrxEntry() {
        return new JBOIDLSTrxEntry();
    }

    /**
     * Create an instance of {@link JBOIDLSTrxEntries }
     * 
     */
    public JBOIDLSTrxEntries createIDLSTrxEntries() {
        return new JBOIDLSTrxEntries();
    }

    /**
     * Create an instance of {@link IDLSTrxServicerequest }
     * 
     */
    public IDLSTrxServicerequest createServicerequest() {
        return new IDLSTrxServicerequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxIMA_XAcctNormalBal")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxIMAXAcctNormalBal(String value) {
        return new JAXBElement<String>(_TrxIMAXAcctNormalBal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxDate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxDate(String value) {
        return new JAXBElement<String>(_TrxDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxStartDate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxStartDate(String value) {
        return new JAXBElement<String>(_TrxStartDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxDebit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxDebit(String value) {
        return new JAXBElement<String>(_TrxDebit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rn")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRn(String value) {
        return new JAXBElement<String>(_Rn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxIMA_AcctCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxIMAAcctCode(String value) {
        return new JAXBElement<String>(_TrxIMAAcctCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxTotal")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxTotal(String value) {
        return new JAXBElement<String>(_TrxTotal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxCredit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxCredit(String value) {
        return new JAXBElement<String>(_TrxCredit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxIMA_AcctNormalBal")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxIMAAcctNormalBal(String value) {
        return new JAXBElement<String>(_TrxIMAAcctNormalBal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxDesc")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxDesc(String value) {
        return new JAXBElement<String>(_TrxDesc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxIMA_XAcctCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxIMAXAcctCode(String value) {
        return new JAXBElement<String>(_TrxIMAXAcctCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxFrom")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxFrom(String value) {
        return new JAXBElement<String>(_TrxFrom_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxEndDate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxEndDate(String value) {
        return new JAXBElement<String>(_TrxEndDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxJournal")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxJournal(String value) {
        return new JAXBElement<String>(_TrxJournal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxRefNo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxRefNo(String value) {
        return new JAXBElement<String>(_TrxRefNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TrxType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTrxType(String value) {
        return new JAXBElement<String>(_TrxType_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "", name = "LastUserCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLastUserCode(String value) {
        return new JAXBElement<String>(_LastUserCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "", name = "LastUpdate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLastUpdate(String value) {
        return new JAXBElement<String>(_LastUpdate_QNAME, String.class, null, value);
    }

}
