//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.02 at 04:53:11 PM SGT 
//


package com.pcci.idls.maintenance.rolemodule.jaxbmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for module element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="module">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}id"/>
 *           &lt;element ref="{}description"/>
 *           &lt;element ref="{}effectivedate"/>
 *           &lt;element ref="{}expirydate"/>
 *           &lt;element ref="{}createaccess"/>
 *           &lt;element ref="{}readaccess"/>
 *           &lt;element ref="{}updateaccess"/>
 *           &lt;element ref="{}deleteaccess"/>
 *           &lt;element ref="{}lastupdate"/>
 *           &lt;element ref="{}modifiedby"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "description",
    "effectivedate",
    "expirydate",
    "createaccess",
    "readaccess",
    "updateaccess",
    "deleteaccess",
    "lastupdate",
    "modifiedby"
})
@XmlRootElement(name = "module")
public class Module {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String effectivedate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String expirydate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String createaccess;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String readaccess;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String updateaccess;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String deleteaccess;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lastupdate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String modifiedby;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the effectivedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectivedate() {
        return effectivedate;
    }

    /**
     * Sets the value of the effectivedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectivedate(String value) {
        this.effectivedate = value;
    }

    /**
     * Gets the value of the expirydate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpirydate() {
        return expirydate;
    }

    /**
     * Sets the value of the expirydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpirydate(String value) {
        this.expirydate = value;
    }

    /**
     * Gets the value of the createaccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateaccess() {
        return createaccess;
    }

    /**
     * Sets the value of the createaccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateaccess(String value) {
        this.createaccess = value;
    }

    /**
     * Gets the value of the readaccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadaccess() {
        return readaccess;
    }

    /**
     * Sets the value of the readaccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadaccess(String value) {
        this.readaccess = value;
    }

    /**
     * Gets the value of the updateaccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateaccess() {
        return updateaccess;
    }

    /**
     * Sets the value of the updateaccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateaccess(String value) {
        this.updateaccess = value;
    }

    /**
     * Gets the value of the deleteaccess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeleteaccess() {
        return deleteaccess;
    }

    /**
     * Sets the value of the deleteaccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeleteaccess(String value) {
        this.deleteaccess = value;
    }

    /**
     * Gets the value of the lastupdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastupdate() {
        return lastupdate;
    }

    /**
     * Sets the value of the lastupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastupdate(String value) {
        this.lastupdate = value;
    }

    /**
     * Gets the value of the modifiedby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifiedby() {
        return modifiedby;
    }

    /**
     * Sets the value of the modifiedby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifiedby(String value) {
        this.modifiedby = value;
    }

}
