//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.14 at 10:10:42 PM PHT 
//


package com.pcci.idls.maintenance.users.jaxbmodel;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.pcci.idls.maintenance.users.jaxbmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Phone_QNAME = new QName("", "phone");
    private final static QName _Middlename_QNAME = new QName("", "middlename");
    private final static QName _Roleid_QNAME = new QName("", "roleid");
    private final static QName _Lastlogon_QNAME = new QName("", "lastlogon");
    private final static QName _Userid_QNAME = new QName("", "userid");
    private final static QName _Lastname_QNAME = new QName("", "lastname");
    private final static QName _Firstname_QNAME = new QName("", "firstname");
    private final static QName _Modifiedby_QNAME = new QName("", "modifiedby");
    private final static QName _Expirydate_QNAME = new QName("", "expirydate");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _Lastupdate_QNAME = new QName("", "lastupdate");
    private final static QName _Email_QNAME = new QName("", "email");
    private final static QName _Locked_QNAME = new QName("", "locked");
    private final static QName _Pword_QNAME = new QName("", "pword");
    private final static QName _Pwordeffectivedate_QNAME = new QName("", "pwordeffectivedate");
    private final static QName _Effectivedate_QNAME = new QName("", "effectivedate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.pcci.idls.maintenance.users.jaxbmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sessionid }
     * 
     */
    public Sessionid createSessionid() {
        return new Sessionid();
    }

    /**
     * Create an instance of {@link JBOUser }
     * 
     */
    public JBOUser createUser() {
        return new JBOUser();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link UserServicerequest }
     * 
     */
    public UserServicerequest createServicerequest() {
        return new UserServicerequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "phone")
    public JAXBElement<BigInteger> createPhone(BigInteger value) {
        return new JAXBElement<BigInteger>(_Phone_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "middlename")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMiddlename(String value) {
        return new JAXBElement<String>(_Middlename_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "roleid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRoleid(String value) {
        return new JAXBElement<String>(_Roleid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastlogon")
    public JAXBElement<String> createLastlogon(String value) {
        return new JAXBElement<String>(_Lastlogon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userid")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUserid(String value) {
        return new JAXBElement<String>(_Userid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLastname(String value) {
        return new JAXBElement<String>(_Lastname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "firstname")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFirstname(String value) {
        return new JAXBElement<String>(_Firstname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "modifiedby")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createModifiedby(String value) {
        return new JAXBElement<String>(_Modifiedby_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "expirydate")
    public JAXBElement<String> createExpirydate(String value) {
        return new JAXBElement<String>(_Expirydate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lastupdate")
    public JAXBElement<String> createLastupdate(String value) {
        return new JAXBElement<String>(_Lastupdate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "locked")
    public JAXBElement<BigInteger> createLocked(BigInteger value) {
        return new JAXBElement<BigInteger>(_Locked_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pword")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPword(String value) {
        return new JAXBElement<String>(_Pword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pwordeffectivedate")
    public JAXBElement<String> createPwordeffectivedate(String value) {
        return new JAXBElement<String>(_Pwordeffectivedate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "effectivedate")
    public JAXBElement<String> createEffectivedate(String value) {
        return new JAXBElement<String>(_Effectivedate_QNAME, String.class, null, value);
    }

}
