//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.20 at 03:04:07 PM SGT 
//


package com.pcci.idls.maintenance.client.jaxbmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for ClientService element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="ClientService">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}transaction"/>
 *           &lt;element ref="{}IMA_ClientID"/>
 *           &lt;element ref="{}IMA_ClientName"/>
 *           &lt;element ref="{}IMA_ClientCode"/>
 *           &lt;element ref="{}LastUserCode"/>
 *           &lt;element ref="{}LastUpdate"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transaction",
    "imaClientID",
    "imaClientName",
    "imaClientCode",
    "lastUserCode",
    "lastUpdate"
})
@XmlRootElement(name = "ClientService")
public class ClientServiceModel {

    @XmlElement(required = true)
    protected Transaction transaction;
    @XmlElement(name = "IMA_ClientID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String imaClientID;
    @XmlElement(name = "IMA_ClientName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String imaClientName;
    @XmlElement(name = "IMA_ClientCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String imaClientCode;
    @XmlElement(name = "LastUserCode", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lastUserCode;
    @XmlElement(name = "LastUpdate", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lastUpdate;

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link Transaction }
     *     
     */
    public Transaction getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transaction }
     *     
     */
    public void setTransaction(Transaction value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the imaClientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMAClientID() {
        return imaClientID;
    }

    /**
     * Sets the value of the imaClientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMAClientID(String value) {
        this.imaClientID = value;
    }

    /**
     * Gets the value of the imaClientName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMAClientName() {
        return imaClientName;
    }

    /**
     * Sets the value of the imaClientName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMAClientName(String value) {
        this.imaClientName = value;
    }

    /**
     * Gets the value of the imaClientCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIMAClientCode() {
        return imaClientCode;
    }

    /**
     * Sets the value of the imaClientCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIMAClientCode(String value) {
        this.imaClientCode = value;
    }

    /**
     * Gets the value of the lastUserCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUserCode() {
        return lastUserCode;
    }

    /**
     * Sets the value of the lastUserCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUserCode(String value) {
        this.lastUserCode = value;
    }

    /**
     * Gets the value of the lastUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdate() {
        return lastUpdate;
    }

    /**
     * Sets the value of the lastUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdate(String value) {
        this.lastUpdate = value;
    }

}
